sources/api/experiment.md

I read through the [experiment documentation](http://chaostoolkit.org/api/experiment/) and noticed some invalid markdown links. This PR resolves the link issue and removes an extra ` I found.

Fix experiment.md markdown errors

---

sources/reference/tutorials/tolerance.md

Found this small JSON error while browsing the documentation.
Signed-off-by: Simon Lindroos <simon.h.lindroos@gmail.com>

Fix to example JSON uses double quotation marks instead on single ones

---

sources/reference/api/experiment.md

- Fix loaded vault secrets keys in examples (secret group name was used instead of the secret key itself)
- Add missing vault address property missing in configuration (when setting up vault secrets, nothing was clear on how the ctk will talk to the vault server)
- Add json examples for inline secrets & config

fix vault secret examples

---

sources/reference/tutorials/tolerance.md

I have tried to create my own tolerance probe using python function, faced some issues due to syntax errors in example.
Refer: https://docs.chaostoolkit.org/reference/tutorials/tolerance/#advanced-scenarios
Issue 1:
```
INFO] Validating the experiment's syntax
[2021-03-28 19:19:34 ERROR] an activity must have a name
```
Custom tolerance requires `name` field.
Issue 2:
```INFO] Validating the experiment's syntax
ERROR] required argument 'value' is missing from activity
```
In custom tolerance function, `value` argument should be optional otherwise it fails during experiment validation state.

fix the issues in advanced scenario examples

---

.github/workflows/build.yaml
.github/workflows/build_and_deploy.yaml

As per #107, we're not setting up the git submodules in builds, therefore we're not pulling in the walkthrough code
Closes #107

Add submodules during build to include the tutorial code

---

mkdocs.yml
sources/reference/usage/cli.md

This PR tidies up the `mkdocs.yml` plugins as there was some duplicates. It also tidies up `cli.md` to remove the non-accessible video of `chaos --help` and to replace it with a textual block instead.
It also removes specific information around settings for getting notifications as these are covered elsewhere.

Tidy up `cli.md`

---

sources/reference/usage/discover.md

This PR tidies up `discover.md` - it removes the non accessible videos of `chaos discover` and replaces them with textual output

Tidy up `discover.md`

---

sources/reference/usage/init.md
sources/static/css/extra.css

This PR tidies up `init.md` by removing prefixes to commands and adding the class `screen-reader-text` from https://make.wordpress.org/accessibility/handbook/markup/the-css-class-screen-reader-text/ so that we can use the asciinema to display the interactive commands but still provide an accessible way to see what happens.

Tidy up `init.md`

---

mkdocs.yml

This PR adds a section on the CLI in the Reference documentation.
Usually this is where you'd expect such material, but we were only displaying it in `Get Started`

Add the CLI to Reference

---

mkdocs.yml
sources/reference/usage/notification.md

This PR tidies up `notification.md` by removing command prefixes and formatting YAML blocks
It also renames the navigation entry from `Notify` to `Notifications`

Tidy up `notification.md`

---

mkdocs.yml

As per https://www.mkdocs.org/about/release-notes/#backward-incompatible-changes-in-12 and the guidance in https://github.com/mkdocs/mkdocs/issues/2252, the `mkdocs` format for Google Analytics has changed.
This PR amends the format we had and re-enables Google Analytics for chaostoolkit.org

Re-enable Google Analytics with new mkdocs format

---

sources/reference/tutorial.md

Added command to explicitly move to the: `chaostoolkit-documentation-code/tutorials/a-simple-walkthrough` directory
Added GitHub links to the third-party binaries: openssl & pkill

Explicit Directory Directing and GitLinks

---

README.md

Just changes the web link from: https://docs.chaostoolkit.org to https://chaostoolkit.org
closes: #128

Corrected weblink

---

mkdocs.yml
sources/reference/tutorials/containerising.md

This PR adds a section on how to containerise CTK for use locally/in other environments
It also covers off making a bespoke image to include extentions

Add section on Containerising CTK

---

mkdocs.yml
sources/reference/tutorials/ec2.md

This PR adds a guide on how to:
* Create an EC2 instance
* Securely connect to the instance via Session Manager
* Setup CTK on the instance
* Run an experiment on the instance
* Modify IAM policies to enable the experiment to do more/less

Add tutorial on running `chaostoolkit` within an EC2 instance

---

mkdocs.yml
sources/reference/tutorials/batch.md

This PR adds a tutorial on how to run Chaos Toolkit experiments with AWS Batch Jobs
It takes the reader through:
* Creating a containerised setup for Chaos Toolkit
* Setting up IAM Roles and Policies to restrict and enable their Batch Jobs to run
* Creating and running Batch Jobs which will carry out their Chaos Toolkit experiments
* More importantly, within their infrastructures networking limits
Also included is a section on doing this a non-manual way using AWS CDK and
a section on storing the experiments journal in S3 too.

Add tutorial on running Chaos Toolkit in AWS Batch

---

mkdocs.yml
sources/reference/tutorials/ec2.md

This PR adds alternate instructions for setting up CTK on EC2 using AWS CLI
* Enables tabs to switch between the console and the CLI

Add AWS CLI version of EC2 instructions

---

sources/reference/tutorials/batch.md
sources/reference/tutorials/ec2.md

This PR adds AWS CLI commands as alternatives to using the console when following the AWS Batch tutorial
It also tidies up some code block highlighting in the EC2 tutorial

Add AWS CLI flavour for Batch tutorial

---

sources/reference/api/experiment.md

As we no longer have `version` in experiments, we're removing the hint talking about whether it's stable or not.

Remove hint about experiment spec

---

.github/workflows/build.yaml
.github/workflows/build_and_deploy.yaml

I believe what is happening is we're running `submodule update` but this is only updating locally (as if the submodules were on the same machine).
This isn't the case, as our submodule is in a repo on Github, I've added the `--remote` flag to see if this is the fix.

Update the submodule from remote, not local

---

sources/reference/usage/discover.md
sources/reference/usage/init.md
sources/reference/usage/report.md
sources/reference/usage/run.md

To address the issue https://github.com/chaostoolkit/chaostoolkit/issues/304
- discover, init, run, report usage reference documents updated

Update reference documentation by removing invalid katacode tutorial link
